spring.application.name=CareTracev2
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${DATABASE_NAME}
jwt.secret=${JWT_SECRET}
allow.origin=${ALLOW_ORIGIN}
gemini.key=${GEMINI_KEY}
expirtaion.duration=7
rekognition.access.key=${REKOGNITION_ACCESS_KEY}
rekognition.secret.key=${REKOGNITION_SECRET_KEY}
rekognition.region=${REKOGNITION_REGION}
